import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import FeaturesCard from "@/components/Cards/FeaturesCard";

// Fix the design here
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Racunko</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-col">
        <div>
          <Navbar />
        </div>
        <div>
          <div className="centered-container flex-col">
            <div className="">
              <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl">
                Racunko
              </h1>
            </div>
            <div>
              <p className="">
                Racunko is a simple and easy to use invoice management system.
              </p>
            </div>
          </div>
          <div className="flex space-x-5">
            <div>
              <FeaturesCard />
            </div>
          </div>

        </div>

      </div>

    </>
  );
};


export default Home;
